src/JSB/CasinoBundle/Entity/Entreprise.php
<?php

namespace JSB\CasinoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entreprise
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="JSB\CasinoBundle\Entity\EntrepriseRepository")
 */
class Entreprise
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     */
    private $nom;

    /**
     * @var float
     *
     * @ORM\Column(name="valeur", type="float")
     */
    private $valeur;
    
    /**
     * @ORM\OneToMany(targetEntity="Part", mappedBy="entreprise")
     */
    private $parts;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Entreprise
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set valeur
     *
     * @param float $valeur
     * @return Entreprise
     */
    public function setValeur($valeur)
    {
        $this->valeur = $valeur;

        return $this;
    }

    /**
     * Get valeur
     *
     * @return float 
     */
    public function getValeur()
    {
        return $this->valeur;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->parts = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add parts
     *
     * @param \JSB\CasinoBundle\Entity\Part $parts
     * @return Entreprise
     */
    public function addPart(\JSB\CasinoBundle\Entity\Part $parts)
    {
        $this->parts[] = $parts;

        return $this;
    }

    /**
     * Remove parts
     *
     * @param \JSB\CasinoBundle\Entity\Part $parts
     */
    public function removePart(\JSB\CasinoBundle\Entity\Part $parts)
    {
        $this->parts->removeElement($parts);
    }

    /**
     * Get parts
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getParts()
    {
        return $this->parts;
    }
    
    public function getPartRestantes(){
        return 10 - count($this->getParts());
    }   
}

src/JSB/CasinoBundle/Controller/DefaultController.php
<?php

namespace JSB\CasinoBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use JSB\CasinoBundle\Form\TransactionType;
use JSB\CasinoBundle\Entity\Transaction;
use JSB\CasinoBundle\Form\PartType;
use JSB\CasinoBundle\Entity\Part;

class DefaultController extends Controller {

    /**
     * @Route("/", name="index")
     * @Template()
     */
    public function indexAction() {
        $personneRepo = $this->getDoctrine()->getRepository("JSB\CasinoBundle\Entity\Personne");

        $personnes = $personneRepo->findAll();

        return $this->render('JSBCasinoBundle:Default:index.html.twig', array('personnes' => $personnes));
    }

    /**
     * 
     * @Route("/account/{id}", requirements={"id" = "\d+"}, name="transactions")
     * @Template()
     */
    public function transactionsViewAction($id) {
        $transactionRepo = $this->getDoctrine()->getRepository("JSB\CasinoBundle\Entity\Transaction");
        $transactions = $transactionRepo->findBy(array("personne" => $id), array('dateHeure' => "DESC"));

        $solde = 0;

        foreach ($transactions as $transaction) {
            $solde += $transaction->getMontant();
        }

        return array(
            'transactions' => $transactions,
            'solde' => $solde
        );
    }

    /**
     * 
     * @Route("/addTransaction/{idPersonne}", requirements={"idPersonne" = "\d+"}, name="newTransaction")
     * 
     * @Template()
     */
    public function addTransactionAction(Request $request, $idPersonne) {
        $personneRepo = $this->getDoctrine()->getRepository("JSB\CasinoBundle\Entity\Personne");
        $personne = $personneRepo->find($idPersonne);

        $transaction = new Transaction();
        $transaction->setDescription("Opération en banque");

        $form = $this->createForm(new TransactionType(), $transaction);

        $form->add("Bingo !", "submit");

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $transaction = $form->getData();


            $transaction->setPersonne($personne);

            $this->getDoctrine()->getManager()->persist($transaction);
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash("success", "La transaction a bien été enregistrée ;-)");

            return $this->indexAction();
        }

        return $this->render("JSBCasinoBundle:Default:form.html.twig", array("form" => $form->createView(), "personne" => $personne));
    }

    /**
     * 
     * @Route("/nouveauTour/{i}", name="newTour", requirements={"i" = "\d+"})
     */
    public function nouveauTourAction($i) {
        $personnesRepo = $this->getDoctrine()->getRepository("JSB\CasinoBundle\Entity\Personne");
        $personnes = $personnesRepo->findAll();

        $manager = $this->getDoctrine()->getManager();
        $tauxPositif = $i / 1000;
        $tauxNegatif = round($tauxPositif * 1.75, 2);

        foreach ($personnes as $personne) {

            $solde = $personne->getSolde();
            $temp = new Transaction();

            $temp->setPersonne($personne);

            if ($solde >= 0) {
                $temp->setMontant($solde * $tauxPositif);
                $temp->setDescription("Taux d'interet de fin de tour. Taux d'interet appliqué : " . ($i / 10) . "% et le solde : $solde");
            } else {
                $temp->setMontant($solde * $tauxNegatif);
                $temp->setDescription("Taux de prêt d'argent pour une dette en fin de tour. Taux d'interêt appliqué " . ($tauxNegatif * 100) . " % et le solde en fin de tour : $solde ");
            }
            
            $parts = $personne->getParts();
            
            foreach($parts as $part){
                
                $transaction = new Transaction();
                $transaction->setDescription("Dividende de la part de l'entreprise ".$part->getEntreprise()->getNom());
                $transaction->setMontant($tauxPositif * 1.4 * $part->getEntreprise()->getValeur() / 10);
                $transaction->setPersonne($personne);
                
                $manager->persist($transaction);
            }

            $manager->persist($temp);
        }

        $manager->flush();

        $this->addFlash("success", "Nous sommes passé au prochain tour");

        return $this->redirect($this->generateUrl("index"));
    }

    /**
     * @Route("/entreprises", name="viewEntreprise")
     * @Template()
     */
    public function listEntrepriseAction() {

        $entrepriseRepo = $this->getDoctrine()->getRepository("JSB\CasinoBundle\Entity\Entreprise");
        $entreprises = $entrepriseRepo->findAll();

        return array("entreprises" => $entreprises);
    }

    /**
     * @Route("/addPart/{idEntreprise}", requirements={ "idEntreprise" : "\d+" },  name="entreprise")
     */
    public function addPart(Request $request, $idEntreprise) {
        $entrepriseRepo = $this->getDoctrine()->getRepository("JSB\CasinoBundle\Entity\Entreprise");
        $entreprise = $entrepriseRepo->find($idEntreprise);

        $part = new Part();
        $part->setEntreprise($entreprise);

        $form = $this->createForm(new PartType(), $part);

        $form->add("Bingo !", "submit");

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager = $this->getDoctrine()->getManager();

            $part = $form->getData();
            
            $transaction = new Transaction();
            $transaction->setDescription("Achat d'une part de l'entreprise ".$entreprise->getNom());
            $transaction->setMontant($entreprise->getValeur()/-10);
            $transaction->setPersonne($part->getProprietaire());

            $manager->persist($part);
            $manager->persist($transaction);
            $manager->flush();
            
            $this->addFlash("success", "La part a bien été achetée");
            
            return $this->redirect($this->generateUrl("viewEntreprise"));
        }

        return $this->render("JSBCasinoBundle:Default:form.html.twig", array("form" => $form->createView()));
    }
    
    /**
     * @Route("/viewPart/{idEntreprise}", requirements={ "idEntreprise" : "\d+" },  name="viewPart")
     * @Template()
     */
    public function viewPartAction($idEntreprise){
        $parts = $this->getDoctrine()->getRepository("JSB\CasinoBundle\Entity\Part")->findBy(array('entreprise'=>$idEntreprise));
        
        return array("parts"=>$parts);
    }
    
    /**
     * @Route("/revendrePart/{idPart}", requirements={ "idPart" : "\d+" },  name="revendrePart")
     */
    public function deletePart($idPart){
        
        $part = $this->getDoctrine()->getRepository("JSB\CasinoBundle\Entity\Part")->find($idPart);
        
        $transaction = new Transaction();
        $transaction->setMontant($part->getEntreprise()->getValeur() * 0.85 / 10);
        $transaction->setPersonne($part->getProprietaire());
        $transaction->setDescription("Revente d'une part dans l'entreprise ".$part->getEntreprise()->getNom());
        
        $manager = $this->getDoctrine()->getManager();
        $manager->remove($part);
        $manager->persist($transaction);
        
        $manager->flush();
        
        $this->addFlash("success", "La part a bien été revendue");
        
        return $this->redirect($this->generateUrl("viewEntreprise"));
        
    }

}

src/JSB/CasinoBundle/Resources/views/Default/addTransaction.html.twig
{% extends '::base.html.twig' %}

{% block body %}
        {{ form(form) }}
{% endblock %}

src/JSB/CasinoBundle/Resources/views/Default/form.html.twig
{% extends '::base.html.twig' %}

{% block body %}
        {{ form(form) }}
{% endblock %}

src/JSB/CasinoBundle/Resources/views/Default/index.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <ul>
        {% for personne in personnes %}
            <li><a href="{{ path("transactions",{"id" : personne.id }) }}">{{ personne.nom }} {{ personne.prenom }}</a> (Solde : {{ personne.solde }}) - <a href="{{ path("newTransaction",{ "idPersonne" : personne.id }) }}">Retrait/Dépôt d'argent</a></li>
            {% endfor %}
    </ul>
    <h2>Options de banque</h2>
    <ul>
        <li>Vendre un stand</li>
        <li>Louer un stand</li>
        <li><a href="{{ path("viewEntreprise") }}">Acheter des parts d'une entreprise</a></li>
    </ul>
    <h2>Passer au tour suivant</h2>
    <p>/nouveauTour/<strong>{tauxDInteret}</strong> - Par exemple pour une augmentation de <strong>2,5%</strong> - /nouveauTour/<strong>25</strong></p>
{% endblock %}

src/JSB/CasinoBundle/Resources/views/Default/listEntreprise.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <ul>
        {% for entreprise in entreprises %}
            <li><a href="{{ path("entreprise", { "idEntreprise" : entreprise.id } ) }}">{{ entreprise.nom }}</a> - Prix : {{ entreprise.valeur / 10 }} - Reste {{ entreprise.partRestantes }}
                {% if entreprise.parts|length > 0 %}
                    (<a href="{{ path("viewPart", { "idEntreprise" : entreprise.id }) }}">Voir les parts disctribuées</a>)
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

src/JSB/CasinoBundle/Resources/views/Default/transactionsView.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <h1>Visualisation des transactions</h1>
    <p>Solde : {{ solde }}</p>
    <ul>
        {% for transaction in transactions %}
            <li>{{ transaction.dateHeure|date('h:i') }} # {{ transaction.montant }} : {{ transaction.description }}</li>
        {% endfor %}
    </ul>
{% endblock %}

src/JSB/CasinoBundle/Resources/views/Default/viewPart.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <ul>
        {% for part in parts %}
            <li>Part {{ loop.index }} : {{ part.proprietaire.prenom }} {{ part.proprietaire.nom }} (<a href="{{ path("revendrePart", { 'idPart' : part.id }) }}">Renvendre la part</a> : {{ (part.entreprise.valeur * 0.85) / 10 }})</li>
        {% endfor %}
    </ul>
{% endblock %}